version: '2'
services:

    cassandra:
        image: cassandra:3.10
        ports:
          - "9042:9042"

    tracking_service:
        build: tracking_service
        command: sbt run
        depends_on:
            - cassandra
        network_mode: host
        entrypoint: sh runcassandra.sh

    cli_client:
        build: cli_client
        network_mode: host
        environment:
            - PYTHONUNBUFFERED=0

    test_client:
        build: cli_client
        environment:
            - PYTHONUNBUFFERED=0
        entrypoint: pytest
