version: "3.9"
services:
  rabbitmq:
    container_name: same-rabbit
    hostname: localhost
    environment:
        - RABBITMQ_DEFAULT_USER="guest"
        - RABBITMQ_DEFAULT_PASS="guest"
    volumes:
        - '/home/USER/rabbitmq/:/var/lib/rabbitmq'
    ports:
        - '5673:5672'
        - '15673:15672'
    image: 'rabbitmq:management'
  cassandra:
    image: 'bitnami/cassandra:latest'
    ports:
      - "9042:9042" # Port for native protocol clients

  trackingservice:
    build: trackingservice
    command: sbt run
    depends_on:
      - cassandra
    network_mode: host
    entrypoint: sh cassandra.sh  # setup cassandra