version: "3.9"
services:
  cassandra:
    image: 'bitnami/cassandra:latest'
    ports:
      - "9042:9042" # Port for native protocol clients

  trackingservice:
    build: trackingservice
    command: sbt run
    depends_on:
      - cassandra
    network_mode: host
    entrypoint: sh cassandra.sh
  
  cliclient:
    build: cliclient
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=0
  
  test_client:
    build: cliclient
    environment:
      - PYTHONUNBUFFERED=0
    entrypoint: pytest